spring:
  mongodb:
    uri: mongodb+srv://dty:Dinan%402004@online-db.kqagkqn.mongodb.net/AutoNetManagerDB?retryWrites=true&w=majority&appName=ONLINE-DB

server:
  port: 0
#  8082

eureka:
  client:
    service-url:
      defaultZone: http://vm-node-a.platform:8761/eureka/,http://vm-node-b.platform:8761/eureka/,http://vm-node-c.platform:8761/eureka/

    register-with-eureka: true
    fetch-registry: true
  instance:
#    hostname: localhost
#    prefer-ip-address: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
